### ISSUE TITLE
em-picker does not open

### ISSUE THREAD

**Issue by azazellochg** [3dem/datavis#14]
I installed everything with:
```
  conda create -n emvis python=3.8
  conda activate emvis
  conda install emvis -c conda-forge -c emforge
  pip install datavis
```
I cant start a picker:
```
(emvis) [azazello@xps13-9350 micrographs]$ em-picker 006.mrc 
Traceback (most recent call last):
  File "/home/azazello/.conda/envs/emvis/bin/em-picker", line 10, in <module>
    sys.exit(picker())
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/emvis/apps/picker.py", line 125, in main
    dv.views.showView(_createView, title="EM-PICKER")
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/datavis/views/_utils.py", line 69, in showView
    win = ViewWindow(createViewFunc(), title=title,
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/emvis/apps/picker.py", line 123, in _createView
    return dv.views.PickerView(model, **kwargs)
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/datavis/views/picker_view.py", line 87, in __init__
    self.__setupGUI(**kwargs)
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/datavis/views/picker_view.py", line 134, in __setupGUI
    self.__addMicrographsAction(imgViewToolBar, **kwargs)
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/datavis/views/picker_view.py", line 184, in __addMicrographsAction
    cvImages = ColumnsView(self._model, **kwargs)
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/datavis/views/_columns.py", line 53, in __init__
    self.setModel(model=model,
  File "/home/azazello/.conda/envs/emvis/lib/python3.8/site-packages/datavis/views/_columns.py", line 341, in setModel
    raise Exception('Invalid model: None')
Exception: Invalid model: None
Segmentation fault (core dumped)
```

**Comment by azazellochg** [comment]
I also tried the following:
```
  conda create -n emvis python=3.8
  conda activate emvis
  pip install emcore
  pip install -e datavis
  pip install -e emvis
```
And got the following:
```
Traceback (most recent call last):
  File "/home/azazello/.conda/envs/emvis/bin/em-picker", line 11, in <module>
    load_entry_point('emvis', 'console_scripts', 'em-picker')()
  File "/home/azazello/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/azazello/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/azazello/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/azazello/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/azazello/soft/em-stuff/emvis/emvis/__init__.py", line 8, in <module>
    from . import utils
  File "/home/azazello/soft/em-stuff/emvis/emvis/utils/__init__.py", line 5, in <module>
    from ._image_manager import ImageManager, ImageRef
  File "/home/azazello/soft/em-stuff/emvis/emvis/utils/_image_manager.py", line 8, in <module>
    from datavis.utils import py23
ImportError: cannot import name 'py23' from 'datavis.utils' (/home/azazello/soft/em-stuff/datavis/datavis/utils/__init__.py)
```
